### ISSUE TITLE
Section on Pauli anti-commuting seems suspect

### ISSUE THREAD

**Issue by jlunder** [gecrooks/on_gates#16]
ChStdGates1.tex it says "XY = -YZ" and "ZX = -ZX" -- these look like typos to me? I would expect, from line 22,

```
XY = -YX = iZ \notag \\
YZ = -ZY = iX \notag \\
ZX = -XZ = iY \notag \\
XYZ = iI \notag
```

**Comment by gecrooks** [comment]
Yup, that's certaintly wrong. Thanks for the catch.

**Comment by AndrewPattersonRL** [comment]
Hi - this is fixed in the source, but the pdf hosted at https://threeplusone.com/pubs/on_gates.pdf still has the error
