### ISSUE TITLE
A simple mistake in the name of DiVincenzo

### ISSUE THREAD

**Issue by podxboq** [gecrooks/on_gates#18]
https://github.com/gecrooks/on_gates/blob/964764b32d66ed97cabbeb9b90d0a13e6cf5b01e/on_gates_src/ChIntro.tex#L18

The name of David P. Divencero is David P. DiVincenzo.

**Comment by gecrooks** [comment]
Oops, thanks for the catch. Never a good thing to mangle people's names.
